development:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: "mimouncadosch@gmail.com"
  :password: "mimounsat"
  :enable_starttls_auto: true
production:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: "mimouncadosch@gmail.com"
  :password: "mimounsat"
  :enable_starttls_auto: true

